import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://hes2-ssd-ohs.oracleindustry.com/oam/server/obrareq.cgi?encquery%3DQ%2Bel%2BHba64XDpW85jQ8Yy6KCN3bx03cYU0tpX%2BQzo42vi5YVzpExeRbU3MQHY%2FVb%2BNL7VZjXXAjI13OQi97TP1%2BHTBlKW2He1rOS2izcMWkCsvnnsY9de2%2FIf1pFA3kLuP0VgFTK8AbITCcDACt0cZp1ea92eD1iruLDbLH5mjjdeWt9lkWGQhAOihYTczuum9MZCphUlZFW0bRjEF2j4dbMKl5%2FmxmlGLlDc0fUoIsnay0LF89hRnYf6oChwT8%2FmJ4lPu08AEhuug5mVlXruZ%2BrE1bj61wQokTGYMVqodAY4GY9bqFYV%2FaPnNUIUtvS2FDNEOy3hAEVCBo8nJ9uujZHZ6VVOT6%2B2hifJ4xX%2F3gPyNLTJ9PTEJj2TGBThvdc%20agentid%3DOAM_RoyalPalm%20ver%3D1%20crmethod%3D2%26cksum%3Deaaf4688d76b6988df9cb54486090b9c03aceee2&ECID-Context=1.006ByOBWf5V03zOUuislkH00007_0002CO%3BkXjE');
  await page.getByRole('textbox', { name: 'User Name' }).click();
  await page.getByRole('textbox', { name: 'User Name' }).fill('johant');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Dexter123456#');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('link', { name: 'Click to go to OPERA Cloud' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.goto('https://mtce4.oraclehospitality.eu-frankfurt-1.ocs.oraclecloud.com/OPERA9/opera/operacloud/faces/adf.task-flow?adf.tfId=opera-cloud-index&adf.tfDoc=/WEB-INF/taskflows/opera-cloud-index.xml');
  const page1 = await page1Promise;
  await page.goto('https://mtce4.oraclehospitality.eu-frankfurt-1.ocs.oraclecloud.com/OPERA9/opera/operacloud/faces/opera-cloud-index/OperaCloud');
  await page.locator('[id="pt1\\:oc_pg_pt\\:ode_pg_mnhdr_rght_cntnt_lnk"]').click();
  await page.getByRole('link', { name: 'Change Location' }).click();
  await page.getByText('The Barracks').click();
  await page.getByRole('button', { name: 'Select' }).click();
  await page.locator('[id="pt1\\:oc_pg_pt\\:ode_pg_mnhdr_rght_cntnt_lnk"]').click();
  await page.getByRole('link', { name: 'Change Location' }).click();
  await page.getByText('Waterfront Village').click();
  await page.getByRole('button', { name: 'Select' }).click();
  await page.goto('https://mtce4.oraclehospitality.eu-frankfurt-1.ocs.oraclecloud.com/OPERA9/opera/operacloud/faces/opera-cloud-index/OperaCloud');
  await page.locator('[id="pt1\\:oc_pg_pt\\:ode_pg_mnhdr_rght_cntnt_lnk"]').click();
  await page.getByRole('link', { name: 'Change Location' }).click();
  await page.getByText('The Trade Boutique Hotel').click();
  await page.getByRole('button', { name: 'Select' }).click();
  await page.locator('[id="pt1\\:oc_pg_pt\\:ode_pg_mnhdr_rght_cntnt_lnk"]').click();
  await page.getByRole('link', { name: 'Change Location' }).click();
  await page.getByText('The Crystal Apartments').click();
  await page.getByRole('button', { name: 'Select' }).click();
  await page.goto('https://mtce4.oraclehospitality.eu-frankfurt-1.ocs.oraclecloud.com/OPERA9/opera/operacloud/faces/opera-cloud-index/OperaCloud');
  await page.locator('[id="pt1\\:oc_pg_pt\\:ode_pg_mnhdr_rght_cntnt_lnk"]').click();
  await page.getByRole('link', { name: 'Change Location' }).click();
  await page.getByText('Harbouredge Suites').click();
  await page.getByRole('button', { name: 'Select' }).click();
  await page.goto('https://mtce4.oraclehospitality.eu-frankfurt-1.ocs.oraclecloud.com/OPERA9/opera/operacloud/faces/opera-cloud-index/OperaCloud');
  await page.locator('[id="pt1\\:oc_pg_pt\\:ode_pg_mnhdr_rght_cntnt_lnk"]').click();
  await page.getByRole('link', { name: 'Change Location' }).click();
  await page.getByText('The Barracks').click();
  await page.getByRole('button', { name: 'Select' }).click();
  await page.locator('[id="pt1\\:oc_pg_pt\\:ode_pg_mnhdr_rght_cntnt_lnk"]').click();
  await page.getByRole('link', { name: 'Change Location' }).click();
  await page.getByText('Lawhill Apartments').click();
  await page.getByRole('button', { name: 'Select' }).click();
  await page.locator('[id="pt1\\:oc_pg_pt\\:ode_pg_mnhdr_rght_cntnt_lnk"]').click();
  await page.getByRole('link', { name: 'Change Location' }).click();
  await page.getByText('The Quarter Apartments').click();
  await page.getByRole('button', { name: 'Select' }).click();
  await page.locator('[id="pt1\\:oc_pg_pt\\:ode_pg_mnhdr_rght_cntnt_lnk"]').click();
  await page.getByRole('link', { name: 'Change Location' }).click();
  await page.getByText('The Barracks').click();
  await page.getByRole('button', { name: 'Select' }).click();
});     