import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://hes2-ssd-ohs.oracleindustry.com/oam/server/obrareq.cgi?encquery%3DtaR4ycFSFmNO%2FnT0%2BgBCLOWFMvlv1tE%2Fb23LgnnkFd9eHLrM3L%2FBfDuYexVAc5PIEqg3OuMBPwnlzIEqtV18MbOl92E8B2pgDX4APOZWLXEpnH3TXRegDUBQ2ZwN6GxaaV5kS2Rqk9ZVH%2F4eoln%2F4QxC3aSKFI1JEwashiZojIw1zKe5D3Z%2F9UKv5D4cNMJWMhKhWf0y45pdYgQ97Rlpg3zLPfapIunIPOFWs4guHoexQzRjEHwLZl8IjGKNcF%2BBQs24ODGvYIN5cZgv2BUwgnpaGjwt0yev8x%2BszAorxzL3gKwST3Z6QwepM%2Fym%2F%2BbUb%2BtKvUiUxLFKMPBbg7rI1lSps0%2FAJrirQNzfIB8q5Rkk774%2FcJa9LC1lnr3wD%2BL%2F%20agentid%3DOAM_RoyalPalm%20ver%3D1%20crmethod%3D2%26cksum%3De05da65aa99369a5a9cea827be6b71aacb506440&ECID-Context=1.006BsUAkFzl03zOUuipmWH0001ZW0000%5ER%3BkXjE');
  await page.getByRole('textbox', { name: 'User Name' }).click();
  await page.getByRole('textbox', { name: 'User Name' }).fill('johant');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Dexter123456#');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('link', { name: 'Click to go to OPERA Cloud' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.goto('https://mtce4.oraclehospitality.eu-frankfurt-1.ocs.oraclecloud.com/OPERA9/opera/operacloud/faces/adf.task-flow?adf.tfId=opera-cloud-index&adf.tfDoc=/WEB-INF/taskflows/opera-cloud-index.xml');
  const page1 = await page1Promise;
  await page.goto('https://mtce4.oraclehospitality.eu-frankfurt-1.ocs.oraclecloud.com/OPERA9/opera/operacloud/faces/opera-cloud-index/OperaCloud');
  await page.getByRole('link', { name: 'Bookings' }).click();
  await page.getByText('Room Diary').click();
  await page.getByRole('textbox', { name: 'Room', exact: true }).click();
  await page.getByRole('textbox', { name: 'Room', exact: true }).fill('0317');
  await page.locator('input[name="pt1\\:oc_pg_pt\\:r1\\:1\\:pt1\\:oc_srch_tmpl_kfm3f1\\:ode_bscrn_tmpl\\:oc_srch_fltrs\\:fe22\\:nd1\\:odec_nvdt_it0"]').click();
  await page.locator('input[name="pt1\\:oc_pg_pt\\:r1\\:1\\:pt1\\:oc_srch_tmpl_kfm3f1\\:ode_bscrn_tmpl\\:oc_srch_fltrs\\:fe22\\:nd1\\:odec_nvdt_it0"]').click();
  await page.locator('input[name="pt1\\:oc_pg_pt\\:r1\\:1\\:pt1\\:oc_srch_tmpl_kfm3f1\\:ode_bscrn_tmpl\\:oc_srch_fltrs\\:fe22\\:nd1\\:odec_nvdt_it0"]').fill('07.03.2025');
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.getByText('CI | Antonov, Sergei').click();
  await page.getByRole('link', { name: 'Modify Search Criteria' }).click();
  await page.getByRole('textbox', { name: 'Room', exact: true }).click();
  await page.getByRole('textbox', { name: 'Room', exact: true }).fill('0318');
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.locator('div').filter({ hasText: /^CI \| Redman, Luke$/ }).nth(1).click();
  await page.getByRole('link', { name: 'Modify Search Criteria' }).click();
  await page.getByRole('textbox', { name: 'Room', exact: true }).click();
  await page.getByRole('textbox', { name: 'Room', exact: true }).fill('0319');
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.locator('div').filter({ hasText: /^IH \| Kashavjee Kalan, Neeraj$/ }).nth(2).click();
  await page.getByRole('link', { name: 'Modify Search Criteria' }).click();
  await page.getByRole('textbox', { name: 'Room', exact: true }).click();
  await page.getByRole('textbox', { name: 'Room', exact: true }).fill('0320');
  await page.locator('[id="pt1\\:oc_pg_pt\\:r1\\:1\\:pt1\\:oc_srch_tmpl_kfm3f1\\:ode_bscrn_tmpl\\:oc_srch_swtchr\\:odec_srch_swtchr_advncd_sf\\:odec_srch_swtchr_advncd_srch_btn"]').click();
  await page.getByText('Dickson, Sarima').first().click();
});