import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://hes2-ssd-ohs.oracleindustry.com/oam/server/obrareq.cgi?encquery%3D519oUrl6K8dNK3HF8o1Rk5PyOn6rJ8KFymFP8VrzHV%2FFes1prqKJ1ZmoYBpgjiPv8V4uHO36V%2B0WwYwDoQ9J6f3n1cGhNjMQGgojOYBrukM9tQiLVbsxWBfHCAqgkUVoJMKZP%2BFbhIinDLHNAVRGFK93Ly3mai5IRGXS%2Bs2ukzauLfF3JeQMVJStU6up4g2G1Mz6RfepVgWdo3dxn4zZ9FrX9S%2FWvMpvhOLTw%2Ba4EW3Mr5FD4crpisaSDL1SyjFX8b8xvkUkWAypNnmavR%2BkuA5k5PGIRFGs4wfCHKc2n%2BavqriFArUEkvDSkRUk63lRxIJDppyqnhYPPbZqA9sa9ltBep90yZIxh%2F3cYDB2cgrV2jG%2B6iROi3qIwrFPb%2F6s%20agentid%3DOAM_RoyalPalm%20ver%3D1%20crmethod%3D2%26cksum%3D37d2a56f61644ea77e0f2fb7217bfa6f33501f14&ECID-Context=1.006BsbM%5EEZD03zOUuislkH00025f0001tN%3BkXjE');
  await page.getByRole('textbox', { name: 'User Name' }).click();
  await page.getByRole('textbox', { name: 'User Name' }).fill('johant');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Dexter123456#');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('link', { name: 'Click to go to OPERA Cloud' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.goto('https://mtce4.oraclehospitality.eu-frankfurt-1.ocs.oraclecloud.com/OPERA9/opera/operacloud/faces/adf.task-flow?adf.tfId=opera-cloud-index&adf.tfDoc=/WEB-INF/taskflows/opera-cloud-index.xml');
  const page1 = await page1Promise;
  await page.goto('https://mtce4.oraclehospitality.eu-frankfurt-1.ocs.oraclecloud.com/OPERA9/opera/operacloud/faces/opera-cloud-index/OperaCloud');
  await page.getByRole('link', { name: 'Bookings' }).click();
  await page.getByText('Reservations', { exact: true }).click();
  await page.getByText('Manage Reservation').click();
  await page.getByRole('textbox', { name: 'Arrival From' }).click();
  await page.getByRole('textbox', { name: 'Arrival From' }).fill('07-03-2025');
  await page.getByRole('textbox', { name: 'Room', exact: true }).click();
  await page.getByRole('textbox', { name: 'Room', exact: true }).fill('0317');
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.getByRole('link', { name: 'Antonov, Sergei' }).click();
  await page.getByRole('link', { name: 'Close' }).click();
  await page.getByRole('link', { name: 'Modify Search Criteria' }).click();
  await page.getByRole('textbox', { name: 'Room', exact: true }).click();
  await page.getByRole('textbox', { name: 'Room', exact: true }).fill('0319');
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.getByRole('link', { name: 'Modify Search Criteria' }).click();
  await page.getByRole('textbox', { name: 'Room', exact: true }).click();
  await page.getByRole('textbox', { name: 'Room', exact: true }).fill('0320');
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.getByRole('link', { name: 'Allen, Mark' }).click();
  await page.getByRole('link', { name: 'Close' }).click();
  await page.getByRole('link', { name: 'Modify Search Criteria' }).click();
  await page.getByRole('textbox', { name: 'Room', exact: true }).click();
  await page.getByRole('textbox', { name: 'Room', exact: true }).fill('0321');
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.getByRole('link', { name: 'Modify Search Criteria' }).click();
});