import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://hes2-ssd-ohs.oracleindustry.com/oam/server/obrareq.cgi?encquery%3D2N0Cn5n9bqIzKHmYaP1YxZ%2BqzuqVzA5rt9RZW0fA1oyqBHjCKerxhpwIV4JTjo%2FI4Brs7c4KnHVKro8U4I%2F%2F8NEjr9O4AyASMh5qYKocFKTqzvyQioT2GFtLnNXDbumrFk3i%2FkgZ2HFlJBpj%2FrKT8nu4bhYH6uyUb8zRiuPvvLh1aeYtsBCMMHT8DetY%2FwHjtZuyLWMvANZzAAGraDjGZwoZFyVmg9ACw0pNOTJ4hxT0rcqG5dOfHbvOgmYVl2KbRCGt0qtOevbvgHVnHDBfS2PPvPqN6SXSviuvOqRZIn%2FxGu%2BLSEBCdXYpTlR1WPdRsc1vw2B9ChLYiHrsa9dSSiLfs%2B9VEn0hdjtNvWMKCPCF3%2FoDejVZuVmM5tKYJzCn%20agentid%3DOAM_RoyalPalm%20ver%3D1%20crmethod%3D2%26cksum%3D50060869025c8f152c712f33e1c6c9047e2be000&ECID-Context=1.006BtYPJ9PU03zOUuipmWH0001bn0002K7%3BkXjE');
  await page.getByRole('textbox', { name: 'User Name' }).click();
  await page.getByRole('textbox', { name: 'User Name' }).fill('johant');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Dexter147#');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('textbox', { name: 'User Name' }).click();
  await page.getByRole('textbox', { name: 'User Name' }).fill('johant');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Dexter123456#');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('link', { name: 'Click to go to OPERA Cloud' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.goto('https://mtce4.oraclehospitality.eu-frankfurt-1.ocs.oraclecloud.com/OPERA9/opera/operacloud/faces/adf.task-flow?adf.tfId=opera-cloud-index&adf.tfDoc=/WEB-INF/taskflows/opera-cloud-index.xml');
  const page1 = await page1Promise;
  await page.goto('https://mtce4.oraclehospitality.eu-frankfurt-1.ocs.oraclecloud.com/OPERA9/opera/operacloud/faces/opera-cloud-index/OperaCloud');
  await page.getByRole('link', { name: 'Bookings' }).click();
  await page.getByText('Manage Reservation').click();
  await page.getByRole('textbox', { name: 'Arrival From' }).click();
  await page.getByRole('textbox', { name: 'Arrival From' }).fill('01.01.2025');
  await page.getByRole('textbox', { name: 'Arrival To' }).click();
  await page.getByRole('textbox', { name: 'Arrival To' }).fill('31.12.2025');
  await page.getByTitle('Search and Select Reservation').first().click();
  await page.locator('[id="pt1\\:oc_pg_pt\\:r1\\:1\\:pt1\\:oc_srch_tmpl_167b9q\\:ode_bscrn_tmpl\\:oc_srch_swtchr\\:odec_srch_swtchr_advncd_sf\\:fe25\\:lov7\\:odec_lov_pc\\:odec_lov_tLovTable\\:0\\:odec_lov_ms1\\:odec_mltslct_chkbx"]').click();
  await page.getByRole('button', { name: 'Select', exact: true }).click();
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.getByRole('link', { name: 'View Options' }).click();
  await page.getByText('Export').click();
  await page.getByText('CSV').click();
  await page.getByRole('textbox', { name: 'File Name' }).click();
  await page.getByRole('textbox', { name: 'File Name' }).fill('Opera_Reservations_2025');
  await page.getByRole('link', { name: 'Close' }).click();
  await page.getByRole('link', { name: 'View Options' }).click();
  await page.locator('[id="f1\\:\\:__af_Z_window"]').getByText('Export').click();
  await page.getByText('CSV').click();
  //await page.getByText('ExcelHTML').click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export' }).click();
  const download = await downloadPromise;
});