import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://hes2-ssd-ohs.oracleindustry.com/oam/server/obrareq.cgi?encquery%3DMq55GYfS59jcJZjCL6sVKLZNuUX9r2FXMj%2BJ1iMygWGGKMgd4br3V%2FRVGOWE59Vj8AWZb4nDzlOBGzO%2BLW4il4Fcsfima%2FIJ6PeBMIkREVVdwYvczSUmyZAvM%2F91ihUQgBblOsED%2FfQUK4issu32A1x%2F1nO8qKwpq2u5lGGYx9yDxnZWV8ekbztbx3n5O%2Fj%2BTDVmVWPp7VdSHhMt%2BY0KFFREbhE6KXSLONT78sZ7AKZ5gn%2FH2Hhh%2B5k%2FXZIIBvbZRTxYJPhjgnZbpD3MIcHKw7JbWIGEmu1y3wTEpFNofC4tquAs0IcRsSu6SxdFUH2S4Bz%2BiCUYX4RiM1T3IHRDdZ39VZo%2BC0jB6jqIB%2FhZgIlovscrFcSer2DUh6pM6RTQ%20agentid%3DOAM_RoyalPalm%20ver%3D1%20crmethod%3D2%26cksum%3D6244fe33ff4eeccbcd89b44514ed92bcc201add7&ECID-Context=1.006BwsbW8Wl03zOUuislkH0002f100019Y%3BkXjE');
  await page.getByRole('textbox', { name: 'User Name' }).click();
  await page.getByRole('textbox', { name: 'User Name' }).fill('johant');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Dexter123456#');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('link', { name: 'Click to go to OPERA Cloud' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.goto('https://mtce4.oraclehospitality.eu-frankfurt-1.ocs.oraclecloud.com/OPERA9/opera/operacloud/faces/adf.task-flow?adf.tfId=opera-cloud-index&adf.tfDoc=/WEB-INF/taskflows/opera-cloud-index.xml');
  const page1 = await page1Promise;
  await page.goto('https://mtce4.oraclehospitality.eu-frankfurt-1.ocs.oraclecloud.com/OPERA9/opera/operacloud/faces/opera-cloud-index/OperaCloud');
  await page.getByRole('link', { name: 'Bookings' }).click();
  await page.getByText('Manage Reservation').click();
  await page.getByRole('textbox', { name: 'Arrival From' }).click();
  await page.getByRole('textbox', { name: 'Arrival From' }).click();
  await page.getByRole('textbox', { name: 'Arrival From' }).fill('01.01.2025');
  await page.getByRole('textbox', { name: 'Arrival To' }).click();
  await page.getByRole('textbox', { name: 'Arrival To' }).fill('31.07.2025');
  await page.getByRole('textbox', { name: 'Room', exact: true }).click();
  await page.getByRole('textbox', { name: 'Room', exact: true }).fill('0303');
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.getByRole('link', { name: 'View Options' }).click();
  await page.getByText('Export').click();
  await page.getByText('CSV').click();
  await page.getByRole('textbox', { name: 'File Name' }).click();
  await page.getByRole('textbox', { name: 'File Name' }).fill('0303');
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export' }).click();
  const download = await downloadPromise;
  await page.getByRole('link', { name: 'Modify Search Criteria' }).click();
  await page.getByRole('textbox', { name: 'Room', exact: true }).click();
  await page.getByRole('textbox', { name: 'Room', exact: true }).fill('0304');
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.getByRole('link', { name: 'View Options' }).click();
  await page.getByText('Export').click();
  await page.getByText('CSV').click();
  await page.getByRole('textbox', { name: 'File Name' }).click();
  await page.getByRole('textbox', { name: 'File Name' }).fill('0304');
  const download1Promise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export' }).click();
  const download1 = await download1Promise;
  await page.getByRole('link', { name: 'Modify Search Criteria' }).click();
  await page.getByRole('textbox', { name: 'Room', exact: true }).click();
  await page.getByRole('textbox', { name: 'Room', exact: true }).fill('0305');
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.getByRole('link', { name: 'View Options' }).click();
  await page.getByText('Export').click();
  await page.getByText('CSV').click();
  await page.getByRole('textbox', { name: 'File Name' }).click();
  await page.getByRole('textbox', { name: 'File Name' }).fill('0305');
  const download2Promise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export' }).click();
  const download2 = await download2Promise;
});