

  await page.getByRole('link', { name: 'Bookings' }).click();
  await page.getByText('Manage Reservation').click();
  await page.getByRole('textbox', { name: 'Arrival From' }).click();
  await page.getByRole('textbox', { name: 'Arrival From' }).fill('01.01.2025');
  await page.getByRole('textbox', { name: 'Arrival To' }).click();
  await page.getByRole('textbox', { name: 'Arrival To' }).fill('31.07.2025');
  await page.getByRole('textbox', { name: 'Room', exact: true }).click();
  await page.getByRole('textbox', { name: 'Room', exact: true }).fill('0308');
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.getByRole('link', { name: 'View Options' }).click();
  await page.getByText('Export').click();
  await page.getByRole('textbox', { name: 'File Name' }).click();
  await page.getByRole('textbox', { name: 'File Name' }).fill('0308');
  await page.getByRole('textbox', { name: 'Document Title' }).click();
  await page.getByRole('textbox', { name: 'Document Title' }).fill('0308');
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export' }).click();
  const download = await downloadPromise;
  await page.getByRole('link', { name: 'Modify Search Criteria' }).click();
  await page.getByRole('textbox', { name: 'Room', exact: true }).click();
  await page.getByRole('textbox', { name: 'Room', exact: true }).fill('0309');
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.getByRole('link', { name: 'View Options' }).click();
  await page.getByText('Export').click();
  await page.getByRole('textbox', { name: 'File Name' }).click();
  await page.getByRole('textbox', { name: 'File Name' }).fill('0309');
  await page.getByRole('textbox', { name: 'Document Title' }).click();
  await page.getByRole('textbox', { name: 'Document Title' }).fill('0309');
  const download1Promise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export' }).click();
  const download1 = await download1Promise;
  await page.getByRole('link', { name: 'Modify Search Criteria' }).click();
});


import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://hes2-ssd-ohs.oracleindustry.com/oam/server/obrareq.cgi?encquery%3DsZVWmZHMZNfIHJ8K6IX%2FJBgb5tTjDYJNJk0dPw9uAHPcHVmcZHIT1N%2BTs3uQ7sA1J2bRwb5Fgr24U%2F4PwiCxLoKD2TXyAHr2KseTO9AboigqGnyjNBlvJDd4cp%2FLWvn%2F1di8WECs6NRZ7s%2FJk8EuPeVWkdw%2Bo2s%2BIrvLi5%2FX8XR3nN%2FjLY%2FKDINHuwujGDF3rQV1PFFjtT0mMiEhMygnlBlZEkXhPRJ6ARDGwz6Qsj9gkENdkzGDlYKFatyK7F0J8VoUrEcoEg6MZDKH54wo8BniRtDzsByOH3QUCgw%2Fb0UPc8TwqknAlEhLYByTMmc9Nfm5BFqwGZ%2FsuUl8QiSevGRg5MDePToInlacUf04ooedP%2BKsVfqXRJZeyTJmmpZF%20agentid%3DOAM_RoyalPalm%20ver%3D1%20crmethod%3D2%26cksum%3Defe935eaae211b29334376c8bdbd46902659f03d&ECID-Context=1.006BvkePXH_03zOUuipmWH0006YI0001dc%3BkXjE');
  await page.getByRole('textbox', { name: 'User Name' }).click();
  await page.getByRole('textbox', { name: 'User Name' }).fill('johant');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Dexter123456#');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('link', { name: 'Click to go to OPERA Cloud' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.goto('https://mtce4.oraclehospitality.eu-frankfurt-1.ocs.oraclecloud.com/OPERA9/opera/operacloud/faces/adf.task-flow?adf.tfId=opera-cloud-index&adf.tfDoc=/WEB-INF/taskflows/opera-cloud-index.xml');
  const page1 = await page1Promise;
  await page.goto('https://mtce4.oraclehospitality.eu-frankfurt-1.ocs.oraclecloud.com/OPERA9/opera/operacloud/faces/opera-cloud-index/OperaCloud');
  await page.getByRole('link', { name: 'Bookings' }).click();
  await page.getByText('Reservations', { exact: true }).click();
  await page.getByText('Manage Reservation').click();
  await page.getByRole('textbox', { name: 'Arrival From' }).click();
  await page.getByRole('textbox', { name: 'Arrival From' }).fill('01.01.2025');
  await page.getByRole('textbox', { name: 'Arrival To' }).click();
  await page.getByRole('textbox', { name: 'Arrival To' }).fill('31.07.2025');
  await page.getByRole('textbox', { name: 'Room', exact: true }).click();
  await page.getByRole('textbox', { name: 'Room', exact: true }).fill('0308');
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.getByRole('link', { name: 'View Options' }).click();
  await page.getByText('Export').click();
  await page.getByText('CSV').click();
  await page.getByRole('textbox', { name: 'File Name' }).click();
  await page.getByRole('textbox', { name: 'File Name' }).fill('0308');
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export' }).click();
  const download = await downloadPromise;
  await page.getByRole('menuitem', { name: 'View Options' }).click();
  await page.getByRole('link', { name: 'Modify Search Criteria' }).click();
  await page.getByRole('textbox', { name: 'Room', exact: true }).click();
  await page.getByRole('textbox', { name: 'Room', exact: true }).fill('0309');
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.getByRole('link', { name: 'View Options' }).click();
  await page.getByText('Export').click();
  await page.getByText('CSV').click();
  await page.getByRole('textbox', { name: 'File Name' }).click();
  await page.getByRole('textbox', { name: 'File Name' }).fill('0309');
  const download1Promise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export' }).click();
  const download1 = await download1Promise;
});